### ISSUE TITLE
PIP install error on Elementary OS / Ubuntu

### ISSUE THREAD

**Issue by JoshWidrick** [JoshWidrick/jdb#1]
After running `$ python3 -m pip install jdatabase` in Terminal, the following error is shown and the package is not installed. 

```
Collecting jdatabase
  Downloading https://files.pythonhosted.org/packages/6d/b7/50a53da29fd253859d77209246f1361537093d8d385e455798290ff0f634/jdatabase-1.2.0a4.tar.gz
Collecting mysqlclient (from jdatabase)
  Downloading https://files.pythonhosted.org/packages/f4/f1/3bb6f64ca7a429729413e6556b7ba5976df06019a5245a43d36032f1061e/mysqlclient-1.4.2.post1.tar.gz (85kB)
    100% |████████████████████████████████| 92kB 1.1MB/s 
    Complete output from command python setup.py egg_info:
    /bin/sh: 1: mysql_config: not found
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-7mztr2gf/mysqlclient/setup.py", line 16, in <module>
        metadata, options = get_config()
      File "/tmp/pip-build-7mztr2gf/mysqlclient/setup_posix.py", line 51, in get_config
        libs = mysql_config("libs")
      File "/tmp/pip-build-7mztr2gf/mysqlclient/setup_posix.py", line 29, in mysql_config
        raise EnvironmentError("%s not found" % (_mysql_config_path,))
    OSError: mysql_config not found
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-7mztr2gf/mysqlclient/
```

**Comment by JoshWidrick** [comment]
To fix this issue, for any Debian based distro (such as ElementaryOS and Ubuntu), simply execute this command to install as the "mysqlclient" package is depended on C system library.

```
sudo apt-get install libmysqlclient-dev
```

The rerun `pip install jdatabase`
